<?php

@define('IMAGECAT_INSTR', '<b>Hinweis:</b> Das Template unterstützt auf der Startseite je ein begleitendes Bild zu einem Eintrag. Damit dieses Feature funktioniert, muss das Serendipity-Event-Plugin <i>Erweiterte Eigenschaften von Artikeln</i> installiert sein. Zusätzlich muss in der Konfiguration dieses Plugins unter <i>Freie Felder</i> ein Feld namens MagazineCategoryImage (Groß-/Kleinschreibung beachten!) angelegt werden. Dann kann beim Erstellen eines Eintrags diesem unter <i>Erweiterte Optionen</i> ein Bild aus der Mediendatenbank zugewiesen werden. Die empfohlene Größe für ein solches Bild hängt von der Kategorie (siehe unten) ab, welcher der betreffende Eintrag zugeordnet ist.<br><br><b>Kategorien:</b> Das Template stellt Einträge auf der Startseite in drei Bereichen dar. Mit den folgenden Auswahllisten können diesen Kategorien s9y-Kategorien zugeordnet werden. Dabei wird aus der Lead-Kategorie (empfohlene Breite des begleitenden Bildes: maximal 270 Pixel) jeweils der aktuellste Eintrag angezeigt. Aus der Features-Kategorie (empfohlene Breite des begleitenden Bildes: maximal 255 Pixel) werden die drei aktuellsten Einträge als Link angezeigt. Schließlich können drei News-Kategorien ausgewählt werden, aus denen jeweils der aktuellste Eintrag (empfohlene Breite des begleitenden Bildes: maximal 60 Pixel) als verkürzter Teaser angezeigt wird.<br><br>');
@define('MIMBO_CAT_LEAD', 'Lead-Kategorie auswählen');
@define('MIMBO_CAT_FEAT', 'Features-Kategorie auswählen');
@define('MIMBO_CAT_X1', '1. News-Kategorie auswählen');
@define('MIMBO_CAT_X2', '2. News-Kategorie auswählen');
@define('MIMBO_CAT_X3', '3. News-Kategorie auswählen');
@define('MIMBO_CAT_X4', '4. News-Kategorie auswählen');
@define('HORZ_NAV_LINK_TITLE', 'Horiz. Navigation Link');
@define('DROPDOWN_AMOUNT', 'Anzahl der Dropdown Menüpunkte (Styles verwalten-Seite muss danach neu geladen werden; Link zur Startseite des Blogs wird automatisch eingefügt)');
@define('DROPDOWN_TEXT', 'Text Dropdown Menüpunkt');
@define('DROPDOWN_URL', 'URL Dropdown Menüpunkt');
@define('SBMENUES_AMOUNT', 'Anzahl Menüs in der Seitenleiste (Styles verwalten-Seite muss danach neu geladen werden...)');
@define('SBHEADER_TEXT', 'Menü Überschrift');
@define('SBHEADER_URL', 'URL der Menü-Überschrift');
@define('SIDEBARMENUE_AMOUNT', 'Anzahl der Menüpunkte (Styles verwalten-Seite muss danach neu geladen werden ...)');
@define('SIDEBARMENUE_TEXT', 'Text des Menüpunkts');
@define('SIDEBARMENUE_URL', 'URL des Menüpunkts');
@define('SBMENUE_TITLE', 'Menü');
@define('SB_TARGET', 'Wie soll der Link geöffnet werden?');

@define('MIMBO_TAB_X1', '1. Tab Kategorie auswählen');
@define('MIMBO_TAB_X2', '2. Tab Kategorie auswählen');
@define('MIMBO_TAB_X3', '3. Tab Kategorie auswählen');
@define('MIMBO_TAB_X4', '4. Tab Kategorie auswählen');
@define('INFO_TAB', '<p style="color:#FFFFFF; background-color: gray;padding-left:.5em"><b> TAB WINDOW </b></p>');
@define('ENABLECAT_TABA', 'Tab-Fenster aktivieren?');
@define('ENABLECAT_HMENUE', 'Horizontalmenü aktivieren?');
@define('ENABLECAT_LEAD', 'Lead-Kategorie aktivieren?');
@define('MAGAZINE_MODE', 'Magazin Modus aktivieren?');
@define('INFO_LEAD', '<p style="color:#000000; background-color:yellow;padding-left:.5em"><b> Leading WINDOW </b></p>');
@define('INFO_NEWS', '<p style="color:#ffffff; background-color:darkmagenta;padding-left:.5em"><b> News Bereich </b></p>');
@define('INFO_FEAT', '<p style="color:#ffffff; background-color:darkgreen;padding-left:.5em"><b> Featured Bereich WINDOW </b></p>');
@define('INFO_TABNUGAMOUNT', '<p style="color:#ffffff; background-color:orange;padding-left:.5em"><b> TAB Klotz WINDOW (TAB Eingabefelder entstehen nach dem Speichern weiter unten)</b></p>');
@define('INFO_SBARMENUESAMOUNT', '<p style="color:#ffffff; background-color:red;padding-left:.5em"><b> Zusätzliche Menüs (Menüpunkte entstehen nach dem Speichern weiter unten)</b></p>');
@define('INFO_HMENUE', '<p style="color:#ffffff; background-color:#0066FF;padding-left:.5em"><b> Horizontal-Menü (Menüpunkte entstehen nach dem Speichern weiter unten)</b></p>');
@define('TABNUG_AMOUNT', 'Anzahl der TAB-Klotz Windows');
@define('CATBANNER_AMOUNT', 'Anzahl der Kategorie-Banner für Kategorie oder Kategorie-Titelseiten');
@define('NUGWIN_NAME', 'Eindeutiger Name (muss einmalig sein)');
@define('ENABLE_TABX1', '1. Tab Kategorie aktivieren?');
@define('ENABLE_TABX2', '2. Tab Kategorie aktivieren?');
@define('ENABLE_TABX3', '3. Tab Kategorie aktivieren?');
@define('ENABLE_STICKY', '4. Tab Kategorie mit Sticky Einträgen aktivieren?');
@define('SICKY_HEADER', '4. Tab Überschrift (Sticky Einträge) :');
@define('INFO_CBA_AMOUNT', '<p style="color:#ffffff; background-color:olive;padding-left:.5em"><b> Kategorie-Banner (Die Menüpunkte entstehen nach dem Speichern weiter unten)</b></p>');

@define('SB_POSITION', 'Position:');
@define('ENABLE_FOOTER', 'Footer aktivieren?');
@define('MIMBO_CAT_ROL', 'Rollmenü Kategorie auswählen:');
@define('LEFTSIDEBAR_POS', 'Linke Seitenleiste erscheint unter:');
@define('TABNUG_POSITION', 'TAB-Position:');
@define('TABNUG_HEIGHT', 'TAB Höhe in px:');
@define('TABTEXT', 'TAB-Text (html):');
@define('TABNUG_HEIGHT', 'TAB-Überschrift:');
@define('CAT_IMAGE_TITLE', 'Kategorie Image');
@define('CATBANNER_POSITION', 'Position des Kategorie Images:');
@define('IMAGE_TO_CAT', 'Zugehörige Kategorie:');
@define('INFO_ROL', '<p style="color:#000000; background-color:#FFCCFF;padding-left:.5em"><b> Rollmenü-WINDOW </b></p>');
@define('ENABLECAT_ROL', 'Rollmenü aktivieren?');
@define('CATROL_HEADER', 'Rollmenü Überschrift:');
@define('ENABLE_TOPSIDEBAR', 'TAB WINDOW TOP-Seitenleiste aktivieren?');

